export const en = {
    charityBaseReactApp: "CharityBase React App",
    description: "Search charites using the maximum and minimum income filters below. The charities are sorted by the \"Income\" column in ascending order.",
    minimumIncome: "Minimum Income",
    maximumIncome: "Maximum Income",
    charityNameColumn: "Charity Name",
    addressColumn: "Address",
    emailColumn: "E-mail",
    telephoneColumn: "Telephone Number",
    incomeColumn: "Income",
    spendingColumn: "Spending",
    grantsColumn: "Grants",
    grantsTotalColumn: "Total Income from Grants",
    percentageOfGrantsAsIncomeColumn: "Percentage of Grants as Income",
    loading: "Loading",
    noCharitiesFound: "No Charities Found with current min  / max income",
    selection: (x, y, z) => "Showing " + x + " to " + y + " Charity out of " + z, 
    grant: (title, amount, currency, funder) => title + ": " + amount + " " + currency + " awared from " + funder + "\r\n",
};